package shuman.airlineSystem.servlets;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.owasp.esapi.ESAPI;
import org.owasp.esapi.errors.IntrusionException;
import org.owasp.esapi.errors.ValidationException;

import shuman.airlineSystem.classes.User;
import shuman.airlineSystem.classes.UserSystem;


/**
 * Servlet implementation class Login
 */
public class Login extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	private static final String INVALID_LOGIN_PAGE = "registration.jsp?invalidLogin=true";
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Login() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String username, password;
		UserSystem users = new UserSystem();
		HttpSession session = request.getSession();
		boolean isValid;
		User user = (User) session.getAttribute("user");
		if(user == null)
		{
			user = new User();
			try{
				// NOTE: code generated by ASIDE         
			username = ESAPI.validator().getValidInput("Login_username",
					request.getParameter("user"), "SafeString", 200, false);
			password = ESAPI.validator().getValidInput("Login_password", 
					request.getParameter("password"), "SafeString", 200, false);
			isValid = users.isValidUser(username, password);
			if(isValid)
			{
				user.setUser(username);
				session.setAttribute("user", user);
				RequestDispatcher dispatch = request.getRequestDispatcher("flightSearch.jsp");
				dispatch.forward(request, response);
			}
			else
				response.sendRedirect(INVALID_LOGIN_PAGE);
			}
			 catch (ValidationException e) {
				response.sendRedirect(INVALID_LOGIN_PAGE);
				return;
			} catch (IntrusionException e) {
				response.sendRedirect(INVALID_LOGIN_PAGE);
				return;
			}
		}
		else{
			response.sendRedirect("flightSearch.jsp");
		}
		
	}
	

}
