package shuman.airlineSystem.servlets;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.owasp.esapi.ESAPI;
import org.owasp.esapi.errors.IntrusionException;
import org.owasp.esapi.errors.ValidationException;

import shuman.airlineSystem.classes.UserSystem;

/**
 * Servlet implementation class Registration
 */
public class Registration extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Registration() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String username, password, email, dob;
		UserSystem users = new UserSystem();
		try {
			// NOTE: code generated by ASIDE         
			username = ESAPI.validator().getValidInput("getRequestedUser",
				request.getParameter("user"), "SafeString", 200, false);
			password = ESAPI.validator().getValidInput("getrequestedPass",
					request.getParameter("password"), "SafeString", 200, false);
			email = request.getParameter("email");
			dob = request.getParameter("dob");
			users.addUser(username, password, email, dob);
			response.sendRedirect("login.jsp");
		} catch (ValidationException e) {
			// NOTE: default return generated by ASIDE
			return;
		} catch (IntrusionException e) {
			// NOTE: default return generated by ASIDE
			return;
		}
	}

}
